<a href="https://colab.research.google.com/github/kasturikirankumar1101-lab/AI_TOOLS/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import spacy

In [ ]:
nlp = spacy.load('en_core_web_sm')

In [ ]:
nlp.pipeline

In [ ]:
nlp.pipe_names

In [ ]:
s1 = "I found a good resource @ https://example.com, for my NLP training for $200"

In [ ]:
doc = nlp(s1)
print(doc)

In [ ]:
for token in doc:
  print(token)

In [ ]:
[(token,token.i) for token in doc]

In [ ]:
doc[3:8]

In [ ]:
[token for token in doc[3:8] if token.text != '@']

In [ ]:
print(nlp.Defaults.stop_words)

In [ ]:
nlp.vocab['the'].is_stop

In [ ]:
nlp.vocab['good'].is_stop

In [ ]:
s1 = "This is an example sentence with some stop words that we want to remove"

In [ ]:
doc3 = nlp(s1)
token_without_stop_words = [token.text for token in doc3 if token.text.lower() not in nlp.Defaults.stop_words]
print(token_without_stop_words)

In [ ]:
nlp.Defaults.stop_words.add('example')

In [ ]:
nlp.vocab['example'].is_stop

In [ ]:
nlp(s1)
doc3 = nlp(s1)
token_without_stop_words = [token.text for token in doc3 if token.text.lower() not in nlp.Defaults.stop_words]
print(token_without_stop_words)

In [ ]:
nlp.Defaults.stop_words.remove('example')
doc3 = nlp(s1)
token_without_stop_words = [token.text for token in doc3 if token.text.lower() not in nlp.Defaults.stop_words]
print(token_without_stop_words)

In [ ]:
# Stemming
from nltk.stem import PorterStemmer

porter = PorterStemmer()
words = ['Cats','Catering', 'bowling', 'friends', 'routers', 'plyaers', 'playing', 'starting', 'starts', 'started']

for word in words:
  print(word,"--->",porter.stem(word))

In [ ]:
from nltk.stem import SnowballStemmer
snowball = SnowballStemmer(language='english')
words = ['Cats','Catering', 'bowling', 'friends', 'routers', 'plyaers', 'playing', 'starting', 'starts', 'started']

for word in words:
  print(word,"--->",snowball.stem(word))

In [ ]:
# Combining both Tokenizer, stop_word, stemming

text = '''Natural Language Processing Is evolving rapidly in today’s data-driven world, and many organizations are investing heavily in NLP-based solutions to extract meaningful insights from unstructured text data. In 2025, companies are not only analyzing customer feedback but also building intelligent chatbots, automated summarization systems, and real-time translation tools that operate at scale. However, before applying advanced models, it is absolutely essential to perform proper text preprocessing steps such as tokenization, stop word removal, normalization, and stemming or lemmatization. For example, words like "running", "runs", and "ran" should ideally be reduced to a common base form during stemming, while common stop words such as "is", "the", "and", and "in" are typically removed to reduce noise in the dataset. Additionally, handling punctuation marks, special characters (like @, #, $, %), and numerical values such as 123 or 45.67 can significantly impact the quality of the processed text. Consider a scenario where a user writes, "I am LOVING this product!!! It’s absolutely amazing, and I’ve never seen anything better." In this case, tokenization should correctly split the sentence into meaningful tokens, case folding should convert "LOVING" into "loving", and stemming might reduce it to "love". Furthermore, repeated words, elongated expressions like "soooo good", and contractions such as "don’t" or "I’ve" must be handled carefully depending on the use case. While preprocessing may seem simple, it plays a crucial role in ensuring that downstream machine learning models perform efficiently and accurately across diverse datasets.'''

In [ ]:
nlp = spacy.load('en_core_web_sm')
doc = nlp(text)
print(doc)

In [ ]:
tokens = [token for token in doc]
print(tokens)

In [ ]:
# stop_words now
stop_word_doc = [token for token in doc if token.text.lower() not in nlp.Defaults.stop_words]
print(stop_word_doc)

In [ ]:
nlp.vocab["'s"].is_stop
nlp.Defaults.stop_words.remove("natural")

In [ ]:
# Stemming now
from nltk.stem import PorterStemmer
porter = PorterStemmer()

for words in stop_word_doc:

  print(words.text,"----->", porter.stem(words.text.lower()))

In [ ]:
# Stemming now
from nltk.stem import SnowballStemmer
snowball = SnowballStemmer('english')


for words in stop_word_doc:

  print(words.text,"----->", snowball.stem(words.text.lower()))

In [ ]:
print(doc)

In [ ]:
import nltk
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')
wordnet = WordNetLemmatizer()
for words in doc:
  print(words.text,"----->",wordnet.lemmatize(words.text.lower()))

In [ ]:
import spacy
nlp = spacy.load('en_core_web_sm')

In [ ]:
for word in doc:
  print(f"{word.text}----> {word.lemma_}")

In [95]:
import pandas
data = pandas.read_csv('/Restaurant_Reviews.tsv', sep='\t')

In [96]:
data.head()

                                              Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [99]:
data.isnull()

     Review  Liked
0     False  False
1     False  False
2     False  False
3     False  False
4     False  False
..      ...    ...
995   False  False
996   False  False
997   False  False
998   False  False
999   False  False

[1000 rows x 2 columns]

In [100]:
data.isnull().sum()

Review    0
Liked     0
dtype: int64

In [103]:
data['Liked'].value_counts()

Liked
1    500
0    500
Name: count, dtype: int64

In [104]:
data['total_chars'] = data['Review'].apply(lambda x : len(x))

In [105]:
data

                                                Review  Liked  total_chars
0                             Wow... Loved this place.      1           24
1                                   Crust is not good.      0           18
2            Not tasty and the texture was just nasty.      0           41
3    Stopped by during the late May bank holiday of...      1           87
4    The selection on the menu was great and so wer...      1           59
..                                                 ...    ...          ...
995  I think food should have flavor and texture an...      0           66
996                           Appetite instantly gone.      0           24
997  Overall I was not impressed and would not go b...      0           50
998  The whole experience was underwhelming, and I ...      0           91
999  Then, as if I hadn't wasted enough of my life ...      0          134

[1000 rows x 3 columns]

In [113]:
import math
data['Word_count'] = data['Review'].apply(lambda x : len(x.split()))

In [114]:
import spacy
nlp = spacy.load('en_core_web_sm')
def num_of_sents(x):
  return len([sents for sents in nlp(x).sents])

In [117]:

data['Number of Sentenses'] = data['Review'].apply(lambda x :num_of_sents(x))

In [118]:
data

,Review,Liked,total_chars,Word_count,Number of Sentenses
0,Wow... Loved this place.,1,24,4,1
1,Crust is not good.,0,18,4,1
2,Not tasty and the texture was just nasty.,0,41,8,1
3,Stopped by during the late May bank holiday of...,1,87,15,1
4,The selection on the menu was great and so wer...,1,59,12,1
...,...,...,...,...,...
995,I think food should have flavor and texture an...,0,66,12,1
996,Appetite instantly gone.,0,24,3,1
997,Overall I was not impressed and would not go b...,0,50,10,1
998,"The whole experience was underwhelming, and I ...",0,91,16,1
999,"Then, as if I hadn't wasted enough of my life ...",0,134,28,1